#!/usr/bin/env bash
# Read-It one-step installer (macOS, Apple Silicon M2/M3/M4/M5).
#
#   ./install.sh              # venv + deps + native-helper registration
#   ./install.sh --download   # ...plus prefetch the Kokoro weights now
#   ./install.sh doctor       # diagnose helper/registration problems
#
# After this, the only manual step is loading the unpacked extension in
# your browser (see README) — the extension then starts/stops/downloads
# everything else itself. No terminal needed beyond this script.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST_NAME="com.readit.tts"
DOWNLOAD_NOW=0

for arg in "$@"; do
  case "$arg" in
    --download) DOWNLOAD_NOW=1 ;;
    doctor) DOCTOR=1 ;;
    -h|--help) sed -n '2,11p' "$0"; exit 0 ;;
    *) echo "unknown flag: $arg (try --download or doctor)" >&2; exit 1 ;;
  esac
done

say()  { printf '\033[1m[read-it]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[read-it]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[read-it]\033[0m %s\n' "$*" >&2; exit 1; }

APP_SUP="$HOME/Library/Application Support"
CANDIDATES=(
  "$APP_SUP/Google/Chrome"
  "$APP_SUP/Chromium"
  "$APP_SUP/BraveSoftware/Brave-Browser"
  "$APP_SUP/Microsoft Edge"
  "$APP_SUP/Arc/User Data"
  "$APP_SUP/Comet"
  "$APP_SUP/Dia"
)

# --- doctor: diagnose without changing anything ----------------------------------
if [[ "${DOCTOR:-0}" -eq 1 ]]; then
  say "repo: $REPO"
  [[ -x "$REPO/.venv/bin/python" ]] \
    && say "venv python: OK ($("$REPO/.venv/bin/python" -c 'import sys; print(sys.version.split()[0])'))" \
    || warn "venv python MISSING — run ./install.sh"
  [[ -x "$REPO/native/readit_host.sh" ]] \
    && say "helper launcher: OK" \
    || warn "helper launcher MISSING — run ./install.sh"
  echo "--- native-messaging manifests ---"
  found=0
  for base in "${CANDIDATES[@]}"; do
    f="$base/NativeMessagingHosts/$HOST_NAME.json"
    if [[ -f "$f" ]]; then
      found=1
      target="$(python3 -c "import json;print(json.load(open('$f'))['path'])" 2>/dev/null || echo "?")"
      if [[ -x "$target" ]]; then st="OK (launcher runs)"; else st="BROKEN (launcher missing: $target)"; fi
      say "$(basename "$base"): registered — $st"
    else
      if [[ -d "$base" ]]; then say "$(basename "$base"): browser present but NOT registered"; fi
    fi
  done
  [[ "$found" -eq 0 ]] && warn "helper is not registered in ANY browser — run ./install.sh"
  echo "--- weights & ports ---"
  du -shL ~/.cache/huggingface/hub/models--mlx-community--Kokoro-82M-bf16 2>/dev/null \
    || echo "Kokoro weights: not downloaded"
  for port in 8901 8902; do
    if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
      say "port $port: LISTENING ($(lsof -nP -iTCP:"$port" -sTCP:LISTEN -t 2>/dev/null | tr '\n' ' '))"
    else
      say "port $port: free"
    fi
  done
  echo "--- checklist ---"
  echo "Extension id in chrome://extensions must be: dnpkdcbdccnpnmcojaemknfbnfkfkgld"
  exit 0
fi

# --- 1. platform -----------------------------------------------------------
[[ "$(uname -s)" == "Darwin" ]] || die "macOS only (found $(uname -s))."
[[ "$(uname -m)" == "arm64" ]] || die "Apple Silicon required (found $(uname -m)). MLX does not run on Intel Macs."
say "macOS $(sw_vers -productVersion) on $(uname -m) — good."

# --- 2. python ---------------------------------------------------------------
command -v python3 >/dev/null || die "python3 not found. Install Python 3.12 from python.org (or: brew install python@3.12)."
PYVER="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
PYMAJ="$(python3 -c 'import sys; print(sys.version_info.major)')"
PYMIN="$(python3 -c 'import sys; print(sys.version_info.minor)')"
if [[ "$PYMAJ" -lt 3 || "$PYMIN" -lt 10 ]]; then
  die "Python >= 3.10 required (found $PYVER). Install 3.12 from python.org."
fi
say "python3 $PYVER — good."

# --- 3. venv + deps ------------------------------------------------------------
if [[ ! -x "$REPO/.venv/bin/python" ]]; then
  say "creating virtualenv…"
  python3 -m venv "$REPO/.venv"
fi
say "installing python dependencies (a few minutes on first run)…"
"$REPO/.venv/bin/pip" install -q --upgrade pip
"$REPO/.venv/bin/pip" install -q -r "$REPO/server/requirements.txt"
say "dependencies installed."

# --- 4. native-messaging helper --------------------------------------------------
# Browsers read <support-dir>/NativeMessagingHosts/<host>.json. We register
# into every Chromium-based browser actually present on this Mac.
say "registering the native helper…"
LAUNCHER="$REPO/native/readit_host.sh"
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Generated by install.sh — do not edit.
exec "$REPO/.venv/bin/python" "$REPO/native/readit_host.py" "\$@"
EOF
chmod +x "$LAUNCHER"
chmod +x "$REPO/native/readit_host.py"

# (browser CANDIDATES list is defined once near the top and reused here.)
REGISTERED=0
for base in "${CANDIDATES[@]}"; do
  if [[ -d "$base" ]]; then
    dest="$base/NativeMessagingHosts"
    mkdir -p "$dest"
    # NOTE: the extension id is pinned by the "key" in extension/manifest.json,
    # so this origin is identical on every machine.
    cat > "$dest/$HOST_NAME.json" <<EOF
{
  "name": "$HOST_NAME",
  "description": "Read-It local MLX voice server helper",
  "path": "$LAUNCHER",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://dnpkdcbdccnpnmcojaemknfbnfkfkgld/"]
}
EOF
    say "registered for $(basename "$base")"
    REGISTERED=$((REGISTERED + 1))
  fi
done
[[ "$REGISTERED" -gt 0 ]] || warn "no Chromium browser profile found — the manifest will be registered on next run. (Supported: Chrome, Arc, Comet, Brave, Edge, Dia, Chromium.)"

# --- 5. optional weight prefetch ---------------------------------------------------
if [[ "$DOWNLOAD_NOW" -eq 1 ]]; then
  say "prefetching Kokoro weights (~0.7 GB)…"
  "$REPO/.venv/bin/python" "$REPO/native/readit_host.py" --download kokoro
  say "weights cached."
fi

# --- 6. next steps ------------------------------------------------------------------
echo
say "done. One manual step remains (browsers don't allow scripts to install extensions):"
echo "  1. Open  chrome://extensions  (or Arc/Comet/Brave equivalent)"
echo "  2. Enable Developer mode, click “Load unpacked”"
echo "  3. Select:  $REPO/extension"
echo
say "Then click the Novel Reader icon → Open player. Voice, style, and the"
say "local server are all controlled inside the player — nothing else to set up."

# Best effort: open the extensions page in whatever Chromium browser exists.
for app in "Google Chrome" "Arc" "Comet" "Brave Browser" "Microsoft Edge" "Dia" "Chromium"; do
  if [[ -d "/Applications/$app.app" ]]; then
    open -a "$app" "chrome://extensions" 2>/dev/null || true
    say "opened chrome://extensions in $app for you."
    break
  fi
done
