#!/bin/bash
# Generated by install.sh — do not edit.
exec "/Users/mozart/Documents/ml/research/webReader/readit/.venv/bin/python" "/Users/mozart/Documents/ml/research/webReader/readit/native/readit_host.py" "$@"
